### PR TITLE
Up to Production - 18 August 2022

### PR DESCRIPTION
**Pull request by indraprasetya154**
## Ovierview
- Bugfix after release production on 16 August 2022
- Bugfix based on new relic/sentry report

## Changes
- [Add optional chaining for user role](https://github.com/jabardigitalservice/office-services/commit/4344d76375994e3296a3a5f59cec45e8deee66df)
- [Add optional chaining](https://github.com/jabardigitalservice/office-services/commit/3be14d59489f466c2d3b220472280fb7da5599d3)
- [bugfix: handle objective params for old mobile app at document signature detail](https://github.com/jabardigitalservice/office-services/commit/1fd848f2950dd3e0993e890d6d1cc842bcd652dd) 

## Evidence
title: Up to production - 18 August 2022 Mobile API
project: SIKD
participants: @indraprasetya154 @azophy @fajarhikmal214 @samudra-ajri

### CODE REVIEW

**Review by samudra-ajri — APPROVED** [review]

**Comment by azophy** [comment]
sori ini nunggu comment aku yg https://github.com/jabardigitalservice/office-services/pull/484#discussion_r948641504 dulu yak :pray:

**Comment by samudra-ajri** [comment]
> sori ini nunggu comment aku yg [#484 (comment)](https://github.com/jabardigitalservice/office-services/pull/484#discussion_r948641504) dulu yak 🙏

boleh ke sini, Mas.. hhe
https://github.com/jabardigitalservice/office-services/pull/487 :grin:

**Review by fajarhikmal214 — APPROVED** [review]

**Comment by indraprasetya154** [comment]
Ini sudah aman berarti yak @samudra-ajri @azophy ?

**Comment by indraprasetya154** [comment]
confirmed sudah aman ya @samudra-ajri

**Pull request merged**
